# Generated by Django 4.1.7 on 2023-10-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('noOFitems', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('instock', models.CharField(default='avalible', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/images/')),
            ],
        ),
    ]
