# Generated by Django 4.1.7 on 2023-10-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrow',
            field=models.BooleanField(default=False),
        ),
    ]
