# Generated by Django 4.1.7 on 2023-10-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_borrow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='borrowbook',
        ),
    ]
